ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducción y Metas


WIChat es una aplicación basada en el popular concurso "Saber y Ganar" y una versión actualizada de la aplicación WIQ creada por HappySw.
El objetivo de este proyecto es añadir funcionalidad y modernizar la aplicación WIQ para mejor la experiencia de usuario cumpliendo con varios objetivos:

* El aprendizaje por parte de los usuarios de los temas incluidos en las preguntas.
* Mejorar la interfaz de la aplicación y adaptarla a las nuevas funciones introducidas.
* Promover la interacción del usuario con la IA para asistirle.
* Replicar al máximo posible el formato de un concurso de preguntas en WIChat.

=== Vista general de los requisitos

La función principal de WIChat es presentar a los usuarios una serie de preguntas que tienen que tratar de responder correctamente, similar al concurso de preguntas "Saber y Ganar".

Las preguntas tendrán un enunciado adjuntado a una imagen y una serie de respuestas posibles. A más preguntas respondidas correctamente, más puntuación.

Los usuarios pueden interactuar con un LLM que le brinde pistas y ayude al usuario.

**Requisitos de alto nivel:**

. El sistema permitirá a los usuarios no registrados registrarse en la aplicación.
.. El registro pedirá obligatoriamente a los usuarios:
... Un nombre de usuario.
... Un correo.
... Una contraseña.
... La confirmación de esa contraseña.
.. Si el registro es exitoso, se guardará la información del usuario en la base de datos y se le redirigirá a la pantalla principal.
.. Si el registro NO es exitoso, notificará el fallo al usuario.
. El sistema permitirá a los usuarios registrados autentificarse en la aplicación.
.. La autenticación pedirá obligatoriamente a los usuarios:
... Un nombre de usuario.
... Una contraseña.
.. Si la autenticación es exitosa, se rederigirá al usuario registrado a la pantalla principal.
.. Si la autenticación NO es exitosa, notificará el fallo al usuario.
. Los usuarios registrados podrán jugar concursos en los que responderán preguntas.
.. El usuario podrá elegir la temática y dificultad del concurso.
... Las temáticas son variadas y contarán con categorías como banderas, ciudades, etc...
... Habrá cuatro niveles de dificultad que alteren la cantidad de preguntas a contestar y el tiempo para responder la pregunta, fácil, medio, difícil y supervivencia.
... En el modo supervivencia si el usuario falla una pregunta, se acabará el juego automáticamente. Cada 5 preguntas se restará el tiempo que tiene el usuario para responder a la pregunta.
.. Los concursos tiene un límite de tiempo indicado por un temporizador.
... Si el usuario se queda sin tiempo, se pasa a la siguiente pregunta del concurso, siempre que no esté en el modo supervivencia.
.. El usuario puede acumular rachas de puntuación.
... Si el usuario responde varias preguntas consecutivas, se creará una racha que hará que el usuario gane más puntos por pregunta acertada.
.. Las preguntas y respuestas se deben generar automáticamente con información conseguida de WikiData.
... Las preguntas deben incluir una imagen, un enunciado y varias respuestas incorrectas.
... Los datos de la pregunta deben ser guardados en base de datos.
.. Los usuarios registrados pueden interactuar con un LLM.
... En forma de pistas de la pregunta actual.
... En forma de un chat conversacional simulando un "comodín de la llamada".
.. Al acabar el concurso, se le mostrará al usuario información sobre el concurso.
... Se mostrará cuantas preguntas han sido acertadas.
... Se mostrará un botón por si el usuario quisiera volver a jugar otro concurso.
. Los usuarios registrados podrán consultar un histórico de su participación en el sistema con la siguiente información:
.. Número de concursos jugados.
.. Preguntas acertadas y falladas en cada concurso.
.. Tiempo de juego de cada concurso.
.. Puntuación de cada concurso.
. El sistema ofrecerá una API que permita obtener información sobre:
.. Los usuarios registrados en la aplicación. Se puede obtener la siguiente información:
... Su nombre de usuario.
... Los concursos que han jugado.
... Las preguntas acertadas y falladas en los concursos jugados.
... Los tiempos de juego en los concursos jugados.
.. Las preguntas generadas por la aplicación. Se puede obtener la siguiente información:
... Enunciado de la pregunta.
... Respuestas generadas, indicando cual es la correcta.
... Imagen utilizada en la pregunta.

La aplicación, debido a su enfoque para todos los públicos, debe tener un especial enfoque en la usabilidad. Debe ser fácil de usar y tener una curva de aprendizaje poco inclinada.

=== Metas de calidad

[options="header",cols="1,2"]
|===
|Atributo de calidad|Motivación
|Usabilidad|La aplicación, debido a su enfoque para todos los públicos, debe tener un especial enfoque en la usabilidad. Debe ser fácil de usar y tener una curva de aprendizaje poco inclinada.
|Disponibilidad|La aplicación debe estar disponible una gran mayoría del tiempo.
|Rendimiento|El tiempo de respuesta de la aplicación debe ser corto para ofrecer una experiencia de juego fluida y disfrutable
|Interoperabilidad|WIChat tendrá una API con la que se puede obtener información relevante a los usuarios y las preguntas generadas. El sistema obtendrá información de WikiData y se comunicará con un LLM.
|Modificabilidad|El sistema debe ser fácil de cambiar y de añadir nuevas funcionalidades para facilitar futuras actualizaciones.
|Escalabilidad|El sistema tiene que ser escalable para que así, en un futuro, más usuarios puedan disfrutar al mismo tiempo de la app.
|===

Sabiendo los atributos de calidad más relevantes, podemos definir unos requisitos no funcionales adecuados.

**Requisitos no funcionales:**

. El tiempo de aprendizaje de un nuevo usuario debe ser menor a 1 hora.
. El sistema será compatible con Windows, iOS y Linux.
. La aplicación deberá funcionar en navegadores web estándar, asegurando la compatibilidad con versiones recientes de Chrome, Firefox, Safari y Edge.
. El sistema debe ser capaz de operar adecuadamente con bastantes usuarios de forma concurrente.
. El tiempo para iniciar o reiniciar el sistema por si surgiese algún error no puede ser más de 30 minutos.
. El sistema debe emplear Wikidata para construir las preguntas.
. El sistema debe emplear un LLM para formular pistas para el usuario.
. El tiempo en generar las preguntas de un concurso no debe ser mayor a 20 segundos.


=== Stakeholders

[options="header",cols="1,2"]
|===
|Nombre|Metas
|Equipo de desarrollo|Desarrolladores que quieren crear una aplicación robusta. Se usan varias tecnologías nuevas que incitan al aprendizaje por parte del equipo.
|ChattySw|Empresa responsable de WIChat. Quieren un producto satisfactorio que sea a gusto del cliente y que el desarrollo de la misma sea lo más ágil y lo menos costoso posible.
|RTVE|El cliente que pidió el producto. Quiere el mejor producto posible y se beneficia directamente de el.
|Usuarios|Los usuarios de la aplicación. Buscan la mejor experiencia de usuario posible y el aprendizaje derivado de las preguntas respondidas.
|HappySw|Responsables de la version experimental anterior de WIChat. Competidora de ChattySw.
|===