ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Contexto y alcance

En este capítulo se describe el ámbito de WIChat.
Se ven los sistemas de los que depende la aplicación y los usuarios que la usan.

=== Contexto de negocio

[plantuml, "Contexto de negocio WIChat", png]
----
left to right direction
frame "Contexto de negocio WIChat" {
    [Gemini_API]
    [WikiData_API]
    
    package "WIChat" {
    }
    
    Usuario ..> WIChat : Accede
    WIChat ..> Gemini_API : Solicita pistas
    WIChat ..> WikiData_API : Consigue datos
}
----

.Usuario
Cualquier usuario que se disponga a usar la aplicación.
Los usuarios deben de registrarse antes de acceder al juego.
En el juego los usuarios responderán preguntas y aprenderán de ellas.
También pueden consultar sus datos históricos en la aplicación.

.Gemini
Los usuarios pueden interactuar con el LLM "Gemini" a través de WIChat para pedir pistas y asistencia para responder preguntas.

.WikiData
La información necesaria para que la aplicación genere las preguntas automáticamente es obtenida de la API de WikiData.
De esta se sacan los enunciados de las preguntas, las respuestas correctas e incorrectas y las imágenes que se adjuntan a las preguntas.

=== Contexto técnico

[plantuml, "Contexto técnico WIChat", png]
----
frame "Azure_Cloud" {
    package "WIChat" {
         package "Gateway Service"{
               [Gateway_service]
               [OpenApi]
         }
         [Wiki_service]
         [History_service]
         [Llm_service]
         [WebApp]
         package "Users" {
              [Auth_service]
              [User_service]
         }
         package "Base de datos" {
              [Data]
        }
    }
}
[WikiData_API]
[Gemini_API]
() "Usuario"
() "Usuario_API"
Usuario ..> WebApp : HTTP
WebApp ..> Gateway_service
Gateway_service --> Wiki_service
Gateway_service --> Auth_service
Gateway_service --> User_service
Gateway_service --> History_service
Gateway_service --> Llm_service
Wiki_service ..> WikiData_API : SPARQL
Llm_service ..> Gemini_API : Google Cloud
Auth_service ..> Data : Mongoose
User_service ..> Data  : Mongoose
Wiki_service ..> Data : Mongoose
History_service ..> Data : Mongoose
Usuario_API ..> OpenApi : HTTP
----

La arquitectura de WIChat es una estructura basada en microservicios:

.Users
El paquete users se divide en dos paquetes, "Auth service" que se encarga de la autenficación de los usuarios ya registrados
y "Users service", que se encarga del registro de nuevos usuarios. Ambos se comunican con la base de datos para guardar o obetener información.

.Wiki service
Es el servicio encargado de comunicarse con la API de WikiData para generar las preguntas y respuestas mostradas a los usuarios.
Las preguntas generadas son guardadas en base de datos para el historial de los usuarios.

.Gateway service
El gateway se encarga de recibir las peticiones y redirigirlas al servicio correspondiente.
Además será el que tenga la OpenApi con la que el usuario que quiera acceder a esta(representado como Usuario_API) pueda visualizar los datos relacionados a la aplicación, como los usuarios y las preguntas generadas.

.History service
Es el servicio que se encarga con todo lo relacionado con el historial de partidas de la aplicación

.WebApp
Donde se encuentra todo el front-end de la aplicación. Se encargará de pedirle servicios al gateway para que el usuario pueda interactuar con las distintas características de la aplicación.

.Llm service
Es el servicio que se encarga de hacer llamadas a la Api de Gemini.

.MongoDB
Todos los datos de la aplicación se guardarán en una base de datos hecha con MongoDB.