ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Vista de ejecución


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== Registrar usuario



* _Para poder jugar un usuario debe estar registrado_
* _Para registrarse se necesita un nombre de usuario y una contraseña_

[plantuml,"User registration diagram",png]
----

actor Usuario
participant "GatewayService" as GS
participant "UserService" as US
database "Base de datos" as DB

Usuario -> GS: Introducir nombre y contraseña
GS -> US: POST /adduser con el nombre y contraseña
US -> US: Validar los datos requeridos
US -> US: Encriptar contraseña
US -> DB: Guardar usuario en la base de datos
DB -> US: Confirmación de almacenamiento
US -> GS: Confirmación de registro
GS -> Usuario: Mostrar confirmación de registro exitoso

----

=== Inicio de sesión

* _Un usuario ya registrado inicia sesión para poder jugar_
* _El usuario debe introducr su nombre y contraseña correctos_

[plantuml,"Log in diagram",png]
----

actor Usuario
participant "GatewayService" as GS
participant "AuthService" as AS
database "Base de datos" as DB

Usuario -> GS: Introducir nombre y contraseña
GS -> AS: POST /login con el nombre y contraseña
AS -> AS: Validar los datos requeridos
AS -> AS: Validar formato de los datos
AS -> DB: Buscar el usuario que trata de iniciar sesión
DB -> AS: Datos del usuario
AS -> AS: Comparar contraseña utilizando bcrypt
alt Contraseña válida
    AS -> GS: Datos del usuario
    GS -> Usuario: Mostrar confirmación de inicio de sesión
else Contraseña inválida
    AS -> GS: Devolver el error(credenciales inválidas)
    GS -> Usuario: Mostrar el error de autenticación
end

----

=== Generación de preguntas en una partida

* _Las preguntas necesarias para el juego son sacadas de WikiData_

[plantuml,"Play diagram",png]
----

actor Usuario
participant "GatewayService" as GS
participant "WikiService" as WS
participant "WikiData" as WD
database "Base de datos" as DB

Usuario -> GS: Comenzar partida
loop Generación de preguntas
    GS -> WS: Pedir una pregunta
    WS -> WD: Pedir una pregunta
    WD -> WS: Devolver información de la pregunta
    WS -> GS: Devolver opciones y foto de la pregunta
    GS -> Usuario: Mostrar opciones y foto de la pregunta
    Usuario -> GS: Responder a la pregunta
    GS -> WS: Corroborar respuesta
    WS -> GS: Devolver resultado de la pregunta
    GS -> Usuario: Mostrar resultado de la pregunta
end
WS -> DB: Almacenar los resultados finales
WS -> GS: Devolver los resultados finales
GS -> Usuario: Mostrar los resultados finales

----
