ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== User registration



* _A user is registered to be able to play_
* _After being registered, the user can sign in whenever it wants_
* _A username and a password will be needed to be registered_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----

actor User
participant "GatewayService" as GS
participant "UserService" as US
database "DataBase" as DB

User -> GS: Enter username and password
GS -> US: POST /adduser with username and password
US -> US: Validate required fields
US -> US: Encrypt password
US -> DB: Save user in the database
DB -> US: Storage confirmation
US -> GS: User created confirmation
GS -> User: Display user registration success

----

=== Log in

* _A user logs in to play_
* _The user must enter an existing username, with the correct password

[plantuml,"Sequence diagram",png]
----

actor User
participant "GatewayService" as GS
participant "AuthService" as AS
database "Database" as DB

User -> GS: Enters username and password
GS -> AS: POST /login with username and password
AS -> AS: Validate required fields
AS -> AS: Validate input format
AS -> DB: Find user by username
DB -> AS: Return user data
AS -> AS: Compare password using bcrypt
alt Valid password
    AS -> GS: Return user data
    GS -> User: Display authentication success
else Invalid password
    AS -> GS: Return error (Invalid credentials)
    GS -> User: Display authentication error
end

----

=== Question generation for a game

* _The questions required for the game so that the user can play are taken from wikidata

[plantuml,"Sequence diagram",png]
----

actor User
participant "GatewayService" as GS
participant "GameService" as Game
participant "WikiData" as WD
database "DataBase" as DB

User -> GS: Start a game
loop Question generation
    GS -> Game: Asks for a question
    Game -> WD: Asks for a question
    WD -> Game: Question info
    Game -> GS: Question options and photo
    GS -> User: Question options and photo
    User -> GS: Answer to the question
    GS -> Game: Corroborate the answer
    Game -> GS: Answer result
    GS -> User: Display result
end
Game -> DB: Store final results
Game -> GS: Final results
GS -> User: Display final results

----
